### ISSUE TITLE
demo拉取镜像

### ISSUE THREAD

**Issue by DcFixer** [opendilab/DI-orchestrator#19]
DI-orchestrator/config/samples/dijob-gobigger.yaml 中opendilab/ding:ditask-example镜像不存在

**Comment by DcFixer** [comment]
有没有完整能运行的提交任务实例代码呢

**Comment by konnase** [comment]
我们这边看一下哈

**Comment by konnase** [comment]
可以参考这个实例：
```yaml
apiVersion: diengine.opendilab.org/v2alpha1
kind: DIJob
metadata:
  name: serial-test
  # generateName: serial-test-
spec:
  group: "xxx"  # 标记job所属的group
  priority: "normal"  # 表示job的优先级，保留字段，调度中或许可以用到
  backoffLimit: 0  # 重启次数，可以为nil，表示无限重启；默认为3
  cleanPodPolicy: "Running"  # 表示job运行完成之后，如何处理worker pods
  preemptible: false  # 表示job是否允许被抢占，调度中对job资源改动之后涉及到抢占操作
  minReplicas: 1
  maxReplicas: 5
  template:
    spec:
      containers:
      - name: di-container
        image: opendilab/ding:nightly
        imagePullPolicy: Always
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        command: ["/bin/bash", "-c",]
        args:
        - |
          ding -m serial -c dizoo/classic_control/cartpole/config/cartpole_dqn_config.py -s 0
        volumeMounts:
        - name: cache-volume
          mountPath: /dev/shm
      volumes:
      - name: cache-volume
        emptyDir:
          medium: Memory
          sizeLimit: 128Mi

```
具体可以看 quickstart 文档 https://di-engine-docs.readthedocs.io/en/latest/quick_start/index.html
